#!/usr/bin/env -S awk -f

function wrap(str) {
  return sprintf("\"%s\"", str)
}

# skip metadata
/^20..-/ { next }

# skip blank
NF == 0 { next }

# kanji line
/^<span lang="ja">/ {
  sub(".*>", "")
  sub("*", "")
  kanji = $0
  next
}

# english words
{
  gensub(/ \+/, " ", "g")
  split(tolower($0), keywords, /(--|,)/)
  printf "{%s:[", wrap(kanji)
  delete seen
  for (i in keywords) {
    keyword = gensub(/(^ *| *$)/, "", "g", keywords[i])
    # remove duplicates within a card (sakura, sakura problem)
    if (seen[keyword]++) { continue }
    if (i > 1) { printf "," }
    printf "%s", wrap(keyword)
  }
  print "]}"
}

