#!/usr/bin/env -S awk -f

function wrap(str) {
  return sprintf("\"%s\"", str)
}

{
  for (i = 1; i <= NF; i++) {
    for (j = 1; j <= NF; j++) {
      if (i == j) continue
      pairs[$i] = pairs[$i]$j
    }
  }
  # pairs[$1] = pairs[$1]$2
  # pairs[$2] = pairs[$2]$1
}

END {
  for (k in pairs) {
    printf "{%s:[%s", wrap(k), wrap("~" k)
    for (i=1; i<=length(pairs[k]); i++) {
      printf ",%s", wrap("~" substr(pairs[k], i, 1))
    }
    print "]}"
  }
}

