---
- hosts: all
  gather_facts: no
  tasks:

  - name: "release number"
    shell: "date +%Y%m%d%H%M%S"
    register: release_num

  - name: "home directories"
    file:
      dest: "{{item}}"
      owner: atlas
      group: atlas
      state: directory
      recurse: yes
    with_items:
      - "/home/atlas/home/releases/{{release_num.stdout}}"


  - name: "checkout repo"
    git:
      repo: https://github.com/jpalardy/home.git
      dest: /home/atlas/home/releases/{{release_num.stdout}}
      depth: 1

  - name: "create REVISION file"
    shell: git rev-parse --short HEAD > REVISION
    args:
      chdir: /home/atlas/home/releases/{{release_num.stdout}}

  - name: "remove .git directory"
    file:
      path: /home/atlas/home/releases/{{release_num.stdout}}/.git
      state: absent

  - name: "softlink current release"
    file:
      src: /home/atlas/home/releases/{{release_num.stdout}}
      dest: /home/atlas/home/current
      state: link

  - name: "only keep 5 latest releases"
    shell: "ls -t | awk 'NR > 5' | xargs rm -rf"
    args:
      chdir: /home/atlas/home/releases/

