// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var deck_view, search_view, workspace;
    window.deck = new Deck();
    deck_view = new DeckView({
      model: deck,
      el: $('#cards')
    });
    search_view = new SearchView({
      el: $('#search')
    });
    workspace = new Workspace();
    Backbone.history.start();
    deck.fetch();
    return $(document).keypress(function(e) {
      var _ref;
      if ((_ref = e.which) === 47 || _ref === 104) {
        e.preventDefault();
        return $('#search input').focus();
      }
    });
  });

}).call(this);
