// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var deck_view, search_view;
    window.deck = new Deck();
    deck_view = new DeckView({
      model: deck,
      el: $('#cards')
    });
    search_view = new SearchView({
      el: $('#search')
    });
    return deck.fetch();
  });

}).call(this);
