// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var deck_view, search_view, workspace;
    window.deck = new Deck();
    deck_view = new DeckView({
      model: deck,
      el: $('#cards')
    });
    search_view = new SearchView({
      el: $('#search')
    });
    workspace = new Workspace();
    Backbone.history.start();
    return deck.fetch();
  });

}).call(this);
